### PR TITLE
Make my life easier

### PR DESCRIPTION
**Pull request by marksidell**
- Add an `--auth-device` option, to choose the MFA device when I have more than one.
- Add more help to the `--duration` option, to tell me the units and the min and max values.

### CODE REVIEW

**Comment by skemper** [comment]
Can you give an example of a potential device name?  When looking at my own account, the names are long and include parts of my phone number.  I'm not sure it saves us much labor in that case, but maybe my Duo account is a special case.  My devices look like:

```
Please select the device you want to authenticate with:
[ 0 ] MyPhoneName (XXX-XXX-1234)
[ 1 ] Token
```

Judging from this code, it looks like I'd have to use `MyPhoneName (XXX-XXX-1234)` as the argument?

**Comment by marksidell** [comment]
Yes, you'd have to use the same device name that appears in the prompt. If don't know your device names, you could simply run the program the old-fashioned way and record the desired name.

The labor to be saved is when you usually want to use the same device, in which case you can place the name as a param in `.alohomora`. This would also solve the problem you posed to Chouser in his otherwise excellent (IMHO) PR. I have a nifty utility that can securely obtain my password. With his addition and this one, I could automate my use of alohomora.

**Comment by skemper** [comment]
While testing this out, I noticed that if you set `auth-device` to be a Yubikey (or "Token" in Duo parlance), the prompt ends up looking like:

```
~> alohomora
Password: 
Passcode:
```

This confused even me when I first saw it; it looks like alohomora is prompting for the password again.  So if we're going to bypass the lines about choosing a device, I think I want to change that second prompt to "Token Passcode" or similar.  I'm happy to make the commit, just wanted to see what you think first.

**Comment by marksidell** [comment]
Yes, you'd have to use the same device name that appears in the prompt. The labor to be saved is when you usually want to use the same device, in which case you can place the name in `.alohomora`. This would also solve the problem you posed to

**Comment by marksidell** [comment]
Confusing indeed. Do you like `Hardware token passcode:` ?

**Pull request merged**
